### PR TITLE
Update to 0.4.13

### PR DESCRIPTION
**Pull request by benthecarman**
looks like `pnpm install` updated a couple other deps, not sure if that is okay

### CODE REVIEW

**Comment by TonyGiorgio** [comment]
are there any breaking API calls? If so it might be best to include this in the gifting PR.

**Comment by benthecarman** [comment]
> are there any breaking API calls? If so it might be best to include this in the gifting PR.

looking through the diff, there shouldn't be

**Comment by benthecarman** [comment]
tests failing, idk why, maybe i'll just let @futurepaul handle it lol

**Comment by benalleng** [comment]
seems we have broken storage

image

the test fails after encrypting

**Comment by futurepaul** [comment]
yeah good find @benalleng

@benthecarman pretty easy to repro:
go to backup, check the three boxes, then enter an encryption password and hit save. you get that `recursive use` error and then on reload storage is broken

**Comment by futurepaul** [comment]
hmm might not be that cut and dry

if you go to https://signet-app.mutinywallet.com/settings/encrypt and click "encrypt" without entering a password you get the same recursive error, there's just no problem on load. so it's something to do with the decrypt step not the encrypt step I think

**Comment by benthecarman** [comment]
I can reproduce, but everything seems to work? Not sure what the best course of action is here

**Comment by futurepaul** [comment]
New theory: you're returning the "Failed to read data from storage" error rather than the "Incorrect password entered". I'm watching for the incorrect password error so I know to prompt the user to inter their password. if I just hardcode it to prompt the user to enter their password it works fine

**Comment by TonyGiorgio** [comment]
> if you go to https://signet-app.mutinywallet.com/settings/encrypt and click "encrypt" without entering a password you get the same recursive error, there's just no problem on load. so it's something to do with the decrypt step not the encrypt step I think

Nothing's changed here, it's a flacky test.

**Pull request closed without merging**
