### PR TITLE
Add PWA shortcuts for send, receive, and activity

### PR DESCRIPTION
**Pull request by benthecarman**
~~Havent tested this yet (not sure if you can with iOS) but wanted to play around with it~~

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Expose_common_actions_as_shortcuts

### CODE REVIEW

**Comment by benthecarman** [comment]
Got it working for android, needed to use dev version of chrome, can't figure out why the icons aren't showing up. Might be my manifest isn't updating..

https://web.dev/manifest-updates/#cr-desktop-test

image

**Comment by benthecarman** [comment]
Also works on chrome desktop
image

**Comment by benalleng** [comment]
tACK I can see the various shortcuts but I also cannot see the icons. What if you change their fill/background? I noticed on other apps the background is always white. maybe the icons are there, they are just not visible

**Comment by benthecarman** [comment]
> Is there a way to add these shortcuts to the android build? Or does that become more of a rabbit-hole of widgets and stuff

looks like we can use this with capacitor 

https://github.com/NePheus/capacitor-android-shortcuts

**Comment by benalleng** [comment]
That worked!

Screenshot_20230921-182516

**Comment by benthecarman** [comment]
Sweet how should we color these then

**Comment by futurepaul** [comment]
activity
receive
send

**Comment by benalleng** [comment]
Tack

**Comment by TonyGiorgio** [comment]
Still not working for me with vanadium on Android but it's not hurting anything at least.

**Review by futurepaul — APPROVED** [review]
lol so many files. lgtm def checks a lot more boxes on that pwabuilder test

**Pull request merged**
