### PR TITLE
Use delete function for deleting while active

### PR DESCRIPTION
**Pull request by TonyGiorgio**
Depends on https://github.com/MutinyWallet/mutiny-node/pull/671

### CODE REVIEW

**Comment by benthecarman** [comment]
oh i made #402 which handles the case where we cant init a wallet

**Comment by TonyGiorgio** [comment]
> oh i made #402 which handles the case where we cant init a wallet

You didn't mention there was a PR already when I asked why it didn't work :man_facepalming: 

Either way, I think yours doesn't work. 
1. The state just got cleared of mutiny wallet
2. The code that calls this delete method already checks if it's init'd or not and calls `import_json` otherwise. So it's redundant here in the first place.

**Comment by benthecarman** [comment]
> You didn't mention there was a PR already when I asked why it didn't work man_facepalming

I started making it after I said that lol

**Comment by futurepaul** [comment]
cherry-picked to #406

**Pull request closed without merging**
