### PR TITLE
Add eSats for federation amounts

### LINKED ISSUE #861: Show esats for federation sats
Screenshot 2024-02-01 at 11 15 52 AM

Middle one should be esats

### PR DESCRIPTION
**Pull request by benalleng**
Closes #861 

image

image

This is a new prop! curious if @futurepaul wants me to not add a prop for this and go another approach

### CODE REVIEW

**Review by TonyGiorgio — APPROVED** [review]
ACK from me! I was thinking about either doing that, or passing in something string value to parse on but for this, I think `isFederation` also makes sense. I'll defer to @futurepaul

**Review by futurepaul — APPROVED** [review]
nice, thank you!

edit: just noticed the test is failing due to the changed text

Screenshot 2024-02-05 at 1 41 29 PM

I can fix if you want

**Review by futurepaul — CHANGES_REQUESTED** [review]
need to fix the test

**Comment by benalleng** [comment]
Ooops! thought it was just a flaky test, I can fix it

**Comment by futurepaul** [comment]
> Ooops! thought it was just a flaky test

many such cases lol

**Comment by futurepaul** [comment]
> I see it has failed in a few PR's

it's an lsp issue I think, we're looking into it. I'll rerun this test when the lsp is working again

**Review by futurepaul — APPROVED** [review]

**Pull request merged**
