### PR TITLE
Experimental websocket control channel

### PR DESCRIPTION
**Pull request by vfiano**
A work-in-progress experiment allowing another device to generate invoices.

### CODE REVIEW

**Comment by benthecarman** [comment]
This is certainly an interesting idea!

I don't see why you'd use this over nwc though?

**Comment by futurepaul** [comment]
@vfiano this is a fun experiment but I'm going to close because I don't know why we'd merge this into the actual project. perhaps open an issue outlining your thinking and linking to this branch? thanks!

**Comment by vfiano** [comment]
Hey guys! Sorry, I was hacking around last week and didn't mean for it to make work for you.

> I don't see why you'd use this over nwc though?

You're absolutely right, and the answer is because I didn't know about `nwc` until I read this comment. But now that I do I have more hacking to do.

**Comment by benthecarman** [comment]
@vfiano we have nwc support in mutiny-node for paying invoices, happy to add support for creating invoices if you need it

**Pull request closed without merging**
