### PR TITLE
restore

### PR DESCRIPTION
**Pull request by futurepaul**
testing against mutiny-node master. there's a ui now for putting in the words

### CODE REVIEW

**Comment by futurepaul** [comment]
I added a test for restore. run it with `just test`. right now it's failing:

Screenshot 2023-06-30 at 1 36 52 PM

**Comment by TonyGiorgio** [comment]
I'll take a look at some point. Probably something isn't finishing when it comes to the deletion of the old stuff.

**Comment by TonyGiorgio** [comment]
This should fix your issue, can't test until mutiny-web has been upgrade. https://github.com/MutinyWallet/mutiny-node/pull/641

**Comment by futurepaul** [comment]
Screenshot 2023-07-03 at 8 16 48 PM

Screenshot 2023-07-03 at 8 16 59 PM

**Comment by TonyGiorgio** [comment]
Very minor so feel free to ignore, but the text both alignment changes at 10 - 12 

signal-2023-07-05-162352

**Review by TonyGiorgio — APPROVED** [review]

**Pull request merged**
