### PR TITLE
pick a federation on setup

### PR DESCRIPTION
**Pull request by futurepaul**
Screenshot 2024-04-11 at 9 55 33 AM

### CODE REVIEW

**Comment by TonyGiorgio** [comment]
Amazing, I love it. I think the copy could improve, both here and in the setup. Been asked a few times what this means. I think we can explain it a bit better, something that focuses on what it provides the user, and something a little less scary than "use at your own risk" while still communicating that each is a new network. Hard to wrap it all up in a small package, could benefit from a "learn more" screen itself.

**Comment by futurepaul** [comment]
> I think the copy could improve, both here and in the setup. 

I'll take another pass at it. Really hard to explain without a wall of text but I'll try again. I can add a learn more explainer modal for the truly curious.

**Comment by futurepaul** [comment]
@TonyGiorgio updated with the text you provided

**Review by TonyGiorgio — APPROVED** [review]
LFG

**Comment by benthecarman** [comment]
think this broke the playwright test

**Comment by futurepaul** [comment]
> think this broke the playwright test

it was the confirm button's fault

**Pull request merged**
