### PR TITLE
Adding a French-language translation for Mutiny

### PR DESCRIPTION
**Pull request by yaeloss**
After having seen the German version, I put together a French translation of Mutiny Wallet, sourced from the en.json file.

For syntax, I chose to keep the conjugations and commands **informal** to honor the style, flow, and general debauchery of the Mutiny Wallet project. This may be outputting for some (tu and ton instead of vous and votre), but I believe the more casual style will be more appealing and familial to users. 

Future edits from French grammar nerds will correct me if I've erred in this assumption.

I toned down my own Canadian French in favor of international French diction for broader adoption.

Most direct French translations of key Bitcoin terms are sourced from established project translations. Otherwise, I kept the original phrasing from the code base (ie. on-chain, Lightning). In French, most Bitcoin literature has not adopted the translation of "éclair" in favor of the English "Lightning," so I kept that in the original language.

I didn't do anything with keys (sorry guys that's beyond my comprehension), and I used the latest en.json file as my base for this file.

### CODE REVIEW

**Comment by TonyGiorgio** [comment]
great, thank you! Should just be one last little thing to do and that's to add french to the drop down list. Instructions here: https://github.com/MutinyWallet/mutiny-web?tab=readme-ov-file#translating

**Comment by yaeloss** [comment]
Okay, should be completed.

**Comment by benthecarman** [comment]
looks like something is wrong with the formatting, if you run `pnpm format` it will fix

**Comment by yaeloss** [comment]
Seems it was a problem with the languages file. pnpm format was run and apparently fixed.

**Comment by TonyGiorgio** [comment]
Thank you!

**Review by TonyGiorgio — APPROVED** [review]

**Pull request merged**
