### PR TITLE
get rid of unified receive

### PR DESCRIPTION
**Pull request by futurepaul**
No more bip21, just lightning and bitcoin address. need to test this out with ben's upcoming pr so we make sure we can handle all the potential scenarios

### CODE REVIEW

**Comment by futurepaul** [comment]
https://no-more-unified.mutiny-web.pages.dev/

**Review by TonyGiorgio — CHANGES_REQUESTED** [review]
The API calls need to be different. You're still calling for a bip21 address, as indicated by the logs that are checking for an address even when the lightning invoice is the only thing present.

**Comment by TonyGiorgio** [comment]
Screenshot 2024-05-08 at 1 17 19 PM

This is incorrect.

**Comment by TonyGiorgio** [comment]
Also, we should allow someone to just hit continue for 0 amount on chain. There's no reason they need to do anything for it.

**Comment by futurepaul** [comment]
addressed @TonyGiorgio comments and also @benthecarman I think I fixed the flicker #1125

**Comment by futurepaul** [comment]
closes #1126 as well

**Comment by TonyGiorgio** [comment]
I also fix dust amount errors in my fedimint onchain mutiny-node PR, but good to have it in both.

**Review by TonyGiorgio — APPROVED** [review]
Works great! Only nit, why not auto select and minimize once onchain or lightning is clicked? We did that before and I liked it. Not sure if you felt one way or another, but that's the only thing that's weird to me.

**Comment by futurepaul** [comment]
Good idea, i think i had to get rid of that when we had the remember selection checkbox

**Pull request merged**
