### PR TITLE
clean up settings and debug screens

### LINKED ISSUE #122: Make seed word list vertical instead of horizontal
write now the words go

1 2
3 4
5 6...

I think it'd be better if it was

1 4
2 5
3 6...

plz no steal

### LINKED ISSUE #213: Clean up settings page
rename i know what i'm doing button => debug 

move more things to debug page if it's not useful

explain and style

### PR DESCRIPTION
**Pull request by futurepaul**
closes #213 

added a liquidity monitor just because it was bugging me not to know (need to open a channel to see it)

Screenshot 2023-06-07 at 2 32 43 PM

sorted the words for you @benthecarman (closes #122)
Screenshot 2023-06-07 at 2 32 48 PM

added explanations to each backend item. also got rid of network because that should be under the logo on the home screen soon

Screenshot 2023-06-07 at 2 33 03 PM

wrote a wiki page for self hosting def could use some help fleshing it out: https://github.com/MutinyWallet/mutiny-web/wiki/Self-hosting

### CODE REVIEW

**Comment by benthecarman** [comment]
I liked the 12 words at the top of the settings page, think that should be obvoius to get to if the user wants it.

Also seems like you removed the node's connection string. I know we are removing m2m connectoins but was the only place to get the node id, would be good to add that back somewhere.

**Comment by TonyGiorgio** [comment]
It's really hard to select the text for the backup, especially on desktop. Should probably have a copy button somewhere as that's probably what most users are going to do anyways. 

Could the node stop button turn back into a node start button? 

Would love just a some little info about the save state / upload state button. Something that explains you can transfer to a new device but should delete the existing state if you do that.

**Comment by futurepaul** [comment]
> I liked the 12 words at the top of the settings page, think that should be obvoius to get to if the user wants it.

how about right below the liquidity monitor?
Screenshot 2023-06-07 at 3 15 02 PM

**Comment by benthecarman** [comment]
Looks good!

**Comment by futurepaul** [comment]
did all the stuff you guys asked for

Screenshot 2023-06-07 at 4 23 36 PM

Screenshot 2023-06-07 at 4 24 24 PM

Screenshot 2023-06-07 at 4 25 22 PM

**Review by benthecarman — APPROVED** [review]

**Pull request merged**
