### PR TITLE
delete contact

### LINKED ISSUE #168: Unable to delete a Mutiny contact
There is no button or option to delete a contact

### PR DESCRIPTION
**Pull request by futurepaul**
closes #168

### CODE REVIEW

**Comment by benthecarman** [comment]
should wait for [962](https://github.com/MutinyWallet/mutiny-node/pull/962)

**Comment by TonyGiorgio** [comment]
This is no longer blocked.

**Comment by TonyGiorgio** [comment]
Is this good to merge?

**Comment by futurepaul** [comment]
> Is this good to merge?

yeah just need approval from @TonyGiorgio or @benthecarman

**Comment by TonyGiorgio** [comment]
I pled the 5th 

Screenshot 2024-02-05 at 4 18 35 PM

**Review by benthecarman — APPROVED** [review]
just tested, was able to delete a contact successfully

**Comment by 5atoshiNakamoto** [comment]
I see that I can edit a contact now, I don't see an actual way to delete any contact fully.

**Comment by benthecarman** [comment]
This hasn't been released yet. Once it is it'll be a button in the edit contact screen

**Pull request merged**
