### PR TITLE
Change LSP url to olympus

### PR DESCRIPTION
**Pull request by benthecarman**

### CODE REVIEW

**Review by TonyGiorgio — COMMENTED** [review]
Signet too?

**Comment by TonyGiorgio** [comment]
The playwright tests are failing now, which seem to indicate some difference between the old LSP and the new one. That should probably be looked into before we switch over.

**Comment by benthecarman** [comment]
> The playwright tests are failing now, which seem to indicate some difference between the old LSP and the new one. That should probably be looked into before we switch over.

was just things timing out, think I got it working now.

**Review by TonyGiorgio — APPROVED** [review]
Cool. Go ahead and change in cloudflare too, it'll go out on the next deploy.

**Comment by benthecarman** [comment]
> Cool. Go ahead and change in cloudflare too, it'll go out on the next deploy.

done

**Pull request merged**
