### PR TITLE
Bump to rc9

### PR DESCRIPTION
**Pull request by benthecarman**

### CODE REVIEW

**Comment by TonyGiorgio** [comment]
Screenshot 2024-03-27 at 11 41 24 AM

what happened to the recommendation events?

**Comment by TonyGiorgio** [comment]
Why does it say "Created at 13 hours ago" ? Is it not aware of it's actual creation date? That's the updated date.

**Comment by benthecarman** [comment]
It's the time of the event. We can't really get a date otherwise

**Comment by TonyGiorgio** [comment]
> It's the time of the event. We can't really get a date otherwise

Should be "last updated at" then

**Review by TonyGiorgio — CHANGES_REQUESTED** [review]
I still see the recommendation events on master, but not on this PR, so something broke.

**Comment by benthecarman** [comment]
lol we did it at the same time

**Comment by TonyGiorgio** [comment]
Screenshot 2024-03-27 at 2 02 17 PM

Nope, try again

**Comment by TonyGiorgio** [comment]
either get you and paul to remove your recommendation and add it again with a signet tag, or change the mutiny-node code to consider this

**Comment by benthecarman** [comment]
> either get you and paul to remove your recommendation and add it again with a signet tag, or change the mutiny-node code to consider this

Yeah would be better to have paul and I edit our recommendation

**Comment by futurepaul** [comment]
so just login on this pr and recommend it again?

**Comment by benthecarman** [comment]
> so just login on this pr and recommend it again?

yeah, you probably need to comment out the code that checks if you already recommended

**Comment by TonyGiorgio** [comment]
Should there be code to "unrecommend" a mint?

**Comment by benthecarman** [comment]
> Should there be code to "unrecommend" a mint?

probably, don't think we need to block release on it though

**Comment by futurepaul** [comment]
cool, I recommended

Screenshot 2024-03-27 at 2 19 20 PM

**Comment by benthecarman** [comment]
Same

now just shows these two on mainnet for me

image

**Review by TonyGiorgio — APPROVED** [review]
Awesome!

**Pull request merged**
