### PR TITLE
v0.5.1 prod release

### PR DESCRIPTION
**Pull request by TonyGiorgio**
I'll wait until the morning to deploy.

If anyone wants to go ahead and install the testflight version, that would be great.

### CODE REVIEW

**Review by futurepaul — APPROVED** [review]
tested fedimint join / receive / send to ln address on testflight, lgtm

does seem like the ios marketing version didn't get bumped tho?

**Comment by TonyGiorgio** [comment]
> does seem like the ios marketing version didn't get bumped tho?

I keep getting told by you and ben that it is not needed.

**Comment by futurepaul** [comment]
It's not required, i was able to test the latest. But it's nice for keeping track of which build is which.

**Comment by TonyGiorgio** [comment]
It's frustrating trying to figure out when you guys want me to bump the iOS and when you guys don't want me to bump the iOS version. I'm wrong each time, apparently.

**Pull request merged**
