### PR TITLE
Add husky & lint-staged for pre-commit hooks (#1)

### PR DESCRIPTION
**Pull request by thebrandonlucas**
Adds husky and lint-staged for pre-commit linting, formatting, and type-checking.

### CODE REVIEW

**Comment by thebrandonlucas** [comment]
@futurepaul deleted `pnpm.lock` and re-installed.

**Review by futurepaul — APPROVED** [review]
lol that pnpm lock diff... looks like it was long overdue!

thanks for this, sry it took so much back and forth but I think it's in a good place now

(and I've pushed commits without formatting like four times today so def will be happy for the quality of life)

**Comment by thebrandonlucas** [comment]
> lol that pnpm lock diff... looks like it was long overdue!
> 
> thanks for this, sry it took so much back and forth but I think it's in a good place now
> 
> (and I've pushed commits without formatting like four times today so def will be happy for the quality of life)

thanks for being patient while I figured out the conflict issues, and happy to do a small addition on this awesome project! Hopefully this makes the DX better for everyone.

**Comment by TonyGiorgio** [comment]
Looks like a rebase will be needed and then recreate the pnpm lock file again.

**Comment by futurepaul** [comment]
this PR is cursed, idk what's with these build failures

**Comment by futurepaul** [comment]
sry thank you @thebrandonlucas but I'm gonna close this, def been burned too many times by setup complications and this never quite got rock solid. hope we can find another way to collab again soon!

**Comment by thebrandonlucas** [comment]
@futurepaul Sorry it ended up being such a hassle. I'll be back with some more PRs soon! 👊

**Pull request closed without merging**
