### PR TITLE
Bring back encrypted local storage

### PR DESCRIPTION
**Pull request by benthecarman**
This reverts commit 915b253db9dbd1c9dba4fa581a2f92b906c1f120.

### CODE REVIEW

**Review by TonyGiorgio — CHANGES_REQUESTED** [review]
clicking on settings after refreshing with an encryption password set results in `ReferenceError: state is not defined`

**Comment by TonyGiorgio** [comment]
> 23-08-03 17:47:21.537 ERROR [mutiny_wasm::indexed_db:415] Failed to save (device_lock) to indexed db: Failed to read data from storage.

**Comment by benthecarman** [comment]
> clicking on settings after refreshing with an encryption password set results in `ReferenceError: state is not defined`

just pushed a fix

**Review by TonyGiorgio — APPROVED** [review]

**Review by futurepaul — APPROVED** [review]
great job

**Pull request merged**
