### PR TITLE
Add Brazilian Real BRL currency

### PR DESCRIPTION
**Pull request by fernandoporazzi**
- Add **Brazilian Real BRL** currency.
- Order list of currencies alphabetically by `value`.

### CODE REVIEW

**Comment by fernandoporazzi** [comment]
I am puzzled about the failing tests. Errors are related to a test on the `/receive` page, however my changes are in `/settings/currency`

**Comment by benthecarman** [comment]
> I am puzzled about the failing tests. Errors are related to a test on the `/receive` page, however my changes are in `/settings/currency`

might just be our test being flaky

**Comment by futurepaul** [comment]
maybe your sort function is messing up the ordering?

```
//Bitcoin and USD need to be FIAT_OPTIONS[0] and FIAT_OPTIONS[1] respectively, they are called in megaStore.tsx
```

**Comment by fernandoporazzi** [comment]
Yes, the indexes were the issue indeed. I implemented 2 new const to hold the indexes of USD and BTC and they can be used across the application if needed.

**Review by benthecarman — APPROVED** [review]

**Pull request merged**
