### PR TITLE
redeem cashu token

### PR DESCRIPTION
**Pull request by elnosh**
Still a WIP but putting it out there for feedback. This PR is to add page to redeem Cashu token.

It depends on:
- mutiny-node PR: https://github.com/MutinyWallet/mutiny-node/pull/1026
- waila change that added support for parsing Cashu token: https://github.com/MutinyWallet/bitcoin-waila/pull/17

So right now it does not work as is. I'm building both changes mentioned above locally and pointing to them in package.json file.

Couple things still need work/fixing:
- CORS error when calling mint.
- After pressing Redeem button, UI is not responsive because of CORS error. It does however add it to the wallet balance if the mint pays the invoice.
- I was trying cashu tokens generated from different wallets and was getting some errors when parsing some of them (I think this may need changes in Waila)

### CODE REVIEW

**Comment by benthecarman** [comment]
> CORS error when calling mint.

what mint are you using? might need to reach out to who is running it to add the headers

**Comment by elnosh** [comment]
> > CORS error when calling mint.
> 
> what mint are you using? might need to reach out to who is running it to add the headers

I was testing with the moksha instance running on mutinynet -> https://moksha-mutinynet.up.railway.app

**Comment by benthecarman** [comment]
I reached out to him on twitter, hopefully get a response

**Comment by elnosh** [comment]
https://github.com/ngutech21/moksha/issues/234 in Moksha that would probably fix issues with parsing tokens from certain wallets

**Comment by ngutech21** [comment]
> https://moksha-mutinynet.up.railway.app

The mint is already setting CORS-headers. You can check using curl:
```
 curl -v GET https://mint.mutinynet.moksha.cash/v1/info
 GET /v1/info HTTP/2
> Host: mint.mutinynet.moksha.cash
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/2 200 
< content-type: application/json
< content-length: 717
< access-control-allow-origin: *
< vary: origin, access-control-request-method, access-control-request-headers
< date: Fri, 16 Feb 2024 14:57:34 GMT
< server: railway
< 
* Connection #1 to host mint.mutinynet.moksha.cash left intact
....
``` 
What is the specific error you are getting?

**Comment by futurepaul** [comment]
thank you! used the logic in #1038 and made you a co-author

**Pull request closed without merging**
