### PR TITLE
Start of sentry integration

### PR DESCRIPTION
**Pull request by TonyGiorgio**
- [x] TODO option to turn it on/off
- [x] Parse mutiny-node console and decide when to submit errors
- [x] ~~Find a better way to reference users/sessions than the default~~ just anon for now, removed the default
- [x] Source maps / github integration
- [x] Delete all testing data
- [x] Make sure any invoice/txid data is scrubbed client side

### CODE REVIEW

**Comment by TonyGiorgio** [comment]
typescript checking is bogus, this is allowed: https://docs.sentry.io/platforms/javascript/configuration/filtering/#event-hints

**Comment by TonyGiorgio** [comment]
Best to test with the latest with mutiny-node in order to get better results.

**Comment by TonyGiorgio** [comment]
Now requires turning on in the admin tools

**Review by futurepaul — APPROVED** [review]
working well for me, finding panics and errors!

**Pull request merged**
