### PR TITLE
Vibrate on successful send, receive, channel open

### LINKED ISSUE #588: Vibrate on success send and receive
Not sure if we can do this for the web but might be able to for the native apps

### PR DESCRIPTION
**Pull request by benthecarman**
Closes #588

### CODE REVIEW

**Comment by benalleng** [comment]
Doesn't seem to work on Android Chrome or Firefox. Either installed as PWA or just on the Web. I noticed that it did work on Android if the version duration was longer when I tried it on whatpwacando

**Comment by benthecarman** [comment]
upped to 1 second and still not working for me :/

**Comment by benthecarman** [comment]
This is working for me on one of my androids but not another. Not sure if that is just browsers being dumb.

**Comment by benalleng** [comment]
tAck on the apk build works fine there, just another reason to download it i guess.

**Review by futurepaul — APPROVED** [review]
going to leave this to you guys for testing because I don't have a handy android setup right now, but the code looks good / straightforward. I'll chime in more on this when I start doing the ios stuff, guessing this should work for the ios app (obvi not working in ios pwa)

**Review by benalleng — APPROVED** [review]
Figured out my issue, code works well

**Comment by TonyGiorgio** [comment]
Have you ran `just native` yet? There's typically android changes whenever capacitor packages are added but I don't see any android change.

**Comment by benthecarman** [comment]
> Have you ran `just native` yet? There's typically android changes whenever capacitor packages are added but I don't see any android change.

Added that, however it was working without it 🤷‍♂️ . We did already have the permissions for vibration I guess

**Pull request merged**
