### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by benthecarman**
wanna add CI to publish the container

### CODE REVIEW

**Comment by futurepaul** [comment]
I tried to `flyctl launch` it:

Screenshot 2023-09-26 at 6 58 53 PM

**Comment by benthecarman** [comment]
hmm can you try building locally? `docker build -t mutiny-web .`

i was able to deploy to fly https://mutiny-web-test.fly.dev

**Comment by futurepaul** [comment]
> hmm can you try building locally? `docker build -t mutiny-web .`
> 
> i was able to deploy to fly https://mutiny-web-test.fly.dev

turns out I was on an old fly version so that might've been causing it, but I also made some improvements I think fiddling around with fixing it
https://mutiny-test-2.fly.dev/

**Comment by futurepaul** [comment]
```Dockerfile
# Use Node.js as a base image for building the site
FROM node:20-slim AS builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# This is the cooler way to run pnpm these days (no need to npm install it)
RUN corepack enable
COPY . /app
WORKDIR /app

# I think we need git be here because the vite build wants to look up the commit hash
RUN apt update && apt install -y git

# Add the ARG directives for build-time environment variables
ARG VITE_NETWORK="bitcoin"
ARG VITE_PROXY="wss://p.mutinywallet.com"
ARG VITE_ESPLORA="https://mutinynet.com/api"
ARG VITE_LSP="https://lsp.voltageapi.com"
ARG VITE_RGS="https://rgs.mutinynet.com/snapshot/"
ARG VITE_AUTH="https://auth.mutinywallet.com"
ARG VITE_STORAGE="https://storage.mutinywallet.com"
ARG VITE_SELFHOSTED="true"

# Install dependencies
RUN pnpm install --frozen-lockfile

# IDK why but it gets mad if you don't do this
RUN git config --global --add safe.directory /app

# Build the static site
RUN pnpm run build

# Now, use Nginx as a base image for serving the site
FROM nginx:alpine

# Copy the static assets from the builder stage to the Nginx default static serve directory
COPY --from=builder /app/dist/public /usr/share/nginx/html

# Expose the default Nginx port
EXPOSE 80

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]

```

**Review by futurepaul — APPROVED** [review]
lgtm to me. don't know much about the CI docker creation stuff but trust that works?

**Pull request merged**
