### PR TITLE
bump(deps): bitcoin-waila to `0.4.0`

### PR DESCRIPTION
**Pull request by oleonardolima**
bump(deps): bitcoin-waila to 0.4.0

- for cashu token redeem
- for fedimint OOBNotes

### CODE REVIEW

**Comment by oleonardolima** [comment]
I can comeback to this one after the next waila release @benthecarman, any other requirements for cutting a release there ?

**Comment by benthecarman** [comment]
@oleonardolima 

https://github.com/MutinyWallet/bitcoin-waila/releases/tag/v0.4.0

**Comment by oleonardolima** [comment]
@benthecarman @futurepaul Is it normal for the iOS step fail ?

**Comment by futurepaul** [comment]
> @benthecarman @futurepaul Is it normal for the iOS step fail ?

Yeah ios build uses env secrets that aren't available to outside PRs

**Comment by benthecarman** [comment]
Since we added the fedimint dep to waila, we don't want to use the wasm package of it anymore but are instead going to expose through mutiny-node so we don't blow up our download size

I have this PR if you want to try playing around with it https://github.com/MutinyWallet/mutiny-node/pull/1045

**Comment by oleonardolima** [comment]
closing in favor of https://github.com/MutinyWallet/mutiny-node/pull/1045 and https://github.com/MutinyWallet/mutiny-web/pull/894

**Pull request closed without merging**
