### PR TITLE
settings reorg

### PR DESCRIPTION
**Pull request by futurepaul**
Screenshot 2023-06-29 at 10 20 22 AM

a good chunk of the work toward the new settings stuff in figma, basic goal was to make a place to land the new nwc stuff, so now I'm ready for that

### CODE REVIEW

**Comment by TonyGiorgio** [comment]
- Lightning channels page is completely blank if there is not a channel. Should probably say something. 

Otherwise super clean!

**Comment by futurepaul** [comment]
> * Lightning channels page is completely blank if there is not a channel. Should probably say something.

good catch

**Comment by benthecarman** [comment]
this is sexy af

**Comment by benthecarman** [comment]
`Backup` being red makes it look like a scary button even thought it is quite the opposite. I feel like the debug tools should be red so those look scary

**Comment by TonyGiorgio** [comment]
"Admin Page" would be a better name than "Kitchen Sink"

**Review by TonyGiorgio — APPROVED** [review]

**Pull request merged**
